<?xml version="1.0"?>
<package format="2">
  <name>laser-tag_nav_bringup</name>
  <version>0.1.0</version>
  <description>Gazebo worlds and bringup resources for the laser-tag navigation project.</description>

  <maintainer email="maintainer@example.com">laser-tag_nav maintainers</maintainer>
  <license>BSD-3-Clause</license>

  <buildtool_depend>catkin</buildtool_depend>

  <exec_depend>gazebo_ros</exec_depend>
  <exec_depend>laser-tag_nav_description</exec_depend>
  <exec_depend>roslaunch</exec_depend>

  <export>
  </export>
</package>
